# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f23dbf3f3bd5b7570ac13ca7a6b114b98e174c4a12ebf20bb9960bcdb23987a4f9da718dcde4c63b35e2890174f24d6bf01f43ea8e511dcf91f4b434f646cb91

test:
  secret_key_base: 34235cef51a895714d9103c33be6497742f02d949b60b1eff2a82033cce85c75359be3562a545c9adac85336a2e3e7a03bec0dae9fdd3be0910ef4b96e228b32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
